<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Client" targetNamespace="http://j2ee.netbeans.org/wsdl/TravelGoodClient/src/newWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/TravelGoodClient/src/newWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="ClientOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="ClientOperationResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="ClientPortType">
        <operation name="ClientOperation">
            <input name="input1" message="tns:ClientOperationRequest"/>
            <output name="output1" message="tns:ClientOperationResponse"/>
        </operation>
    </portType>
    <binding name="ClientBinding" type="tns:ClientPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ClientOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/TravelGoodClient/src/newWSDL"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/TravelGoodClient/src/newWSDL"/>
            </output>
        </operation>
    </binding>
    <service name="ClientService">
        <port name="ClientPort" binding="tns:ClientBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/ClientService/ClientPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="Client">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="ClientPortTypeRole" portType="tns:ClientPortType"/>
    </plnk:partnerLinkType>
</definitions>
